### ISSUE TITLE
failed to run the code smoothly

### ISSUE THREAD

**Issue by Jiumeizhu** [Drinchai/BloodGen3Module#1]
Thanks for your great work "BloodGen3Module",
I really like this kind of analysis, 
and it is really helpful for blood Modular transcriptional repertoire analyses in rheumatology disease,

However, when I use your package, I found I failed to run the code smoothly,
Then I run the simple example data in the instructions, it always shows the same error as below：

library(BloodGen3Module)
Test_sample = matrix(data = rexp(1000, rate = 0.01), nrow = 14168, ncol = 20)
control_sample = matrix(data = rexp(1000, rate = 0.1),  nrow = 14168, ncol = 10)
data.matrix = data.frame(cbind(Test_sample, control_sample))
data.matrix$Symbol = Module_listGen3$Gene
data.matrix = aggregate(data.matrix[,-31], FUN = mean, by = list(data.matrix$Symbol))
rownames(data.matrix) = data.matrix$Group.1
data.matrix$Group.1 = NULL
colnames(data.matrix) = c(paste0(rep("SampleID", 30), 1:30))
sample_ann = data.frame(SampleID = (colnames(data.matrix)), Group_test = c(rep("Test", 20), rep("Control",10)), stringsAsFactors = FALSE)
rownames(sample_ann) = sample_ann$SampleID
Group_limma <- Groupcomparisonlimma(data.matrix, sample_info = sample_ann,
  FC = 1.5, pval = 0.1, FDR = TRUE, Group_column = "Group_test",Test_group = "Test", Ref_group = "Control")

**Error in fold_change(df_raw) : object 'Test_group' not found**

looking forward to your suggestions,
Best wishes,
Honglin

**Comment by Drinchai** [comment]
Hi Honglin,

Thanks for you report. I just updated some functions.It should be OK now. Could you re-install the package and run the analysis again?

**Comment by Jiumeizhu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi Drinchai,
        Thank you so much!I can run it 
smoothly,Best wishes,Honglin
    
        
            
        
    
    
        
        

        
    

    On 1/17/2021 04:29，Drinchai<notifications@github.com> wrote： 



Hi Honglin,
Thanks for you report. I just updated some functions.It should be OK now. Could you re-install the package and run the analysis again?
